name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    #strategy:
      #fail-fast: false
      #matrix:
        #env: [current, next]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        channels: conda-forge
        channel-priority: true
        activate-environment: anaconda-client-env
        environment-file: envs/default-current.yml
    - name: checking info
      run: conda --version
